services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:8080"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - NODE_ENV=production
    depends_on:
      - mariadb
      - redis
    command: npm run dev

  mariadb:
    image: mariadb:10.5.8
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    #command: --init-file /docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6.0.9
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes

  command_runner:
    build:
      context: .
      dockerfile: Dockerfile.command
    volumes:
      - ./data/mysql:/var/lib/mysql
    depends_on:
      - node_app
